# Generated by Django 5.2 on 2025-05-06 23:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroFirma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Ingreso",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(blank=True, null=True, verbose_name="Comentarios"),
                ),
                (
                    "firma",
                    models.ImageField(
                        upload_to="firmas/%Y/%m/%d/", verbose_name="Firma Digital"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Firma",
                "verbose_name_plural": "Registros de Firmas",
                "ordering": ["-fecha_ingreso"],
            },
        ),
    ]
