# Generated by Django 5.2 on 2025-05-07 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appacceso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrofirma",
            name="fecha_grabacion",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de Grabación (Automática)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registrofirma",
            name="fecha_ingreso",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Fecha de Ingreso (Editable)",
            ),
        ),
    ]
