# Generated by Django 5.2 on 2025-05-10 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appacceso", "0002_registrofirma_fecha_grabacion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre de Sede"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=200, verbose_name="Dirección"),
                ),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "ordering": ["nombre"],
            },
        ),
        migrations.RemoveField(
            model_name="registrofirma",
            name="comentarios",
        ),
        migrations.AddField(
            model_name="registrofirma",
            name="sede",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="appacceso.sede",
                verbose_name="Sede",
            ),
        ),
    ]
