# Generated by Django 4.2.11 on 2025-05-28 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("appacceso", "0003_sede_remove_registrofirma_comentarios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrofirma",
            name="tipo_registro",
            field=models.CharField(
                choices=[("ingreso", "Ingreso"), ("salida", "Salida")],
                default="ingreso",
                max_length=10,
                verbose_name="Tipo de Registro",
            ),
        ),
        migrations.AlterField(
            model_name="registrofirma",
            name="fecha_ingreso",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha"
            ),
        ),
    ]
